version: 2
sphinx:
  # Path to your Sphinx configuration file.
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt  # Crea este archivo con sphinx, sphinx-rtd-theme, etc.
